options:
  merge-default-rules: true
  formatter: stylish
# File Options
files:
  include:
    - 'docroot/themes/custom/**/*.scss'
    - 'docroot/modules/custom/**/*.scss'
  ignore:
    - 'docroot/themes/custom/**/fonts/**/*.scss'
    - 'docroot/themes/custom/**/build/.*'
# Rule Configuration
rules:
  indentation:
    - 1
    - size: 2
  variable-name-format:
    - 1
    - allow-leading-underscore: true
  nesting-depth: 0
  placeholder-in-extend: 0
